### PR TITLE
get rid of extra dependency

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by radubrehar** [comment]
Thanks for helping. I'm not convinced this is a very good idea, since I suppose it requires ES7 babel features (stage 1/2?) which not many people have enabled. It's not very standardized yet.

What do you think?

**Comment by Guria** [comment]
I didn't enabled extra stages. Seems it's part of [stage-2](https://github.com/babel/babel/blob/master/packages/babel-preset-stage-2/index.js#L7) now.

In fact I think such small modules could be completely rewritten to clean es5 without `babel` / `webpack` stuff at all :)

PS. There is no good reason to store `build` / `dist` files in vcs. Everything that could be compiled can be part of `npm` package and it is not required to duplicate this stuff in git.

**Comment by radubrehar** [comment]
So let's leave object-assign in place for now.

`dist` is there for people who whould rather consume that directly as a browser included script, though this is not the preferred approach.

**Comment by radubrehar** [comment]
`lib` really needs to be there, since we expect/want everyone using npm to be able to consume the module, without webpack/babel transpilation. Our entry point in package.json is `lib/index.js`

**Comment by Guria** [comment]
https://github.com/zippyui/zippyui.github.io/issues/1

**Pull request closed without merging**
